/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package newgradleproject;

public class Library {
    public int sumInts(int firstNum, int secondNum)
    {
        return firstNum + secondNum;
    }
}
